### ISSUE TITLE
Avez-vous archivé LAG ?

### ISSUE THREAD

**Issue by JulienFalgas** [bobbyblues/webcomics-gatherer#2]
Bonjour,

Je découvre tardivement votre script d'archivage de la série Les Autres Gens. Y ayant consacré ma thèse de doctorat, j'aurais beaucoup aimé conserver une trace de la version numérique de la série (à laquelle j'étais bien sûr abonné de la première heure). Malheureusement, le site a depuis disparu.

Si vous avez une archive, pourriez-vous me contacter depuis mon site perso : http://julien.falgas.fr ?

Merci beaucoup,

Julien Falgas

**Comment by bobbyblues** [comment]
J'ai effectivement une archive créée avec mon propre abonnement, mais je ne peux pas la partager pour des raisons évidentes de droit d'auteur :(
